# This file may be used to create a conda environment using:
# $ conda create --name gprMax --file <this file>

name: gprMax
dependencies:
- python>3.6
- colorama
- cython
- h5py
- jupyter
- matplotlib
- numpy=1.26.2=py311h24aa872_0
- numpy-base=1.26.2=py311hbfb1bba_0y
- pip
- psutil
- scipy
- numpy

- pip:
  - terminaltables
  - numpy
  - tqdm
  - gprmax
 # - mpi4py
 # - pycuda
